export const sampleCsv = `D,Date,Day,City,Theme,Ideas,Must Eats,Transportation,Comments,Essential Japanese,Notes/Bookings
1,5/9,Sat,Tokyo,Arrival & Neon Lights,"Land, Shinjuku (Godzilla head), Golden Gai micro-bars, Omoide Yokocho (Memory Lane), Konbini run",Golden Gai snacks & Omoide Yokocho Yakitori,Narita Express,Landing at 2:30pm JL 55. Low pressure day for wandering. Buy Hanshin Tigers hat at Selection Store.,"Sumimasen (Excuse me), Biiru o kudasai (Beer please), Hitotsu (One)",Get Suica card; Download offline Google Maps; Confirm hotel check-in
2,5/10,Sun,Tokyo,Tradition & Pop Culture,"Meiji Shrine, Yoyogi Park, Harajuku (Takeshita St), Gotokuji Temple","Harajuku Crepes, Katsu Curry",Local Trains,Arrive at Meiji Shrine by 8am to beat crowds. Quiet neighborhood dinner in Setagaya.,"Arigato gozaimasu (Thank you), Kore wa nan desu ka? (What is this?)",Book SHIBUYA SKY in advance (if adding); Meiji Shrine opens at sunrise
3,5/11,Mon,Tokyo,Asakusa & Sumo,"Senso-ji Temple, Asakusa Rickshaw, Sumo Tournament, Ryogoku","Chanko Nabe (Sumo stew), Asakusa Street Food",Local Trains,Rickshaw in the morning (unhurried). Sumo from 2:30-6pm.,"Oishii (Delicious), Itadakimasu (Let's eat)",BOOK SUMO TICKETS; Book Rickshaw (Viator)
4,5/12,Tue,Tokyo,Fuji & Nature,"Fuji Five Lakes, Lakeside cycling, Mt. Fuji Panoramic Ropeway, Oishi Park flowers",Houtou Noodles (local specialty),Bus/Train to Kawaguchiko,May is peak season for flower displays at Oishi Park. Peaceful day.,"Kirei (Beautiful), Kawaii (Cute)",Check visibility forecast for Mt. Fuji
5,5/13,Wed,Tokyo,Gardens & Digital Art,"Shinjuku Gyoen, Daikanyama (Tsutaya Books), Nakameguro Canal, Shibuya Crossing, TeamLab Borderless","Daikanyama cafe lunch, Nakameguro coffee",Local Trains,Skip Tokyo Tower/Skytree. Shibuya at dusk for the neon. teamLab best in evening.,Gochisousama deshita (Thanks for the meal),BOOK TEAMLAB BORDERLESS (weeks ahead)
6,5/14,Thu,Hakone,Hakone Retreat,"Hakone-Yumoto town, Ryokan relaxation, Private Onsen",Kaiseki dinner (in-room),Romancecar,"Slow, restorative day. Decompress in the private outdoor bath.","O-furo (Bath), Sugoi (Amazing)",Book Romancecar (Observation Deck seats)
7,5/15,Fri,Hakone,The Hakone Loop,"Amazake Chaya, Owakudani, Open Air Museum, Lake Ashi Pirate Ship, Hakone Shrine","Black eggs (Kuro-tamago), Mochi and Amazake",Shinkansen to Kyoto,Stone-paved Tokaido road walk. Iconic water torii gate at late afternoon.,"Mizu (Water), Koko wa doko desu ka? (Where am I?)",Buy Hakone Free Pass for the loop
8,5/16,Sat,Kyoto,Travel to Kyoto,"Travel from Hakone, Gion evening walk","Gion snacks, Kyoto pickles",Shinkansen,Low key arrival. Evening geisha district walk is magical.,"Konnichiwa (Hello), Sayonara (Goodbye)",Check geisha etiquette rules
9,5/17,Sun,Kyoto,Zen Gardens & Gold,"Fushimi Inari (6am hike), Nishiki Market, Kinkaku-ji, Ryoan-ji, Philosopher's Path, Nanzen-ji","Nishiki Market street food, Pontocho Alley dinner",Bus/Local Trains,Start at Fushimi Inari by 6am. Ryoan-ji rewards stillness.,"Shizuka ni (Quietly), Kintore (Gold...?)",Early start is non-negotiable for Fushimi Inari
10,5/18,Mon,Arashiyama,Arashiyama Morning,"Bamboo Grove (6am), Tenryu-ji Garden, Togetsukyo Bridge, Iwatayama Monkey Park",Tofu lunch (local specialty),Local Trains,Continue past the main bamboo grove to Jojakko-ji for hidden gems.,"Saru (Monkey), Take (Bamboo)",Book local Arashiyama restaurant for dinner
11,5/19,Tue,Osaka,Osaka Flavors & Old Town,"Kuromon Ichiba, Shinsekai, Tennoji Garden","Takoyaki, Kushikatsu, Market seafood",Local Trains,Swap Amerika-mura for the peaceful Tennoji garden.,Meccha oishii (Super delicious),Bring cash for market stalls
12,5/20,Wed,Osaka,Culture & Baseball,"Sumiyoshi Taisha, Hozenji Yokocho, Hanshin Tigers Game",Koshien Curry & Yakisoba,Hanshin Line to Koshien,Moved game to tonight to free up your final night.,Ganbare! (Go for it!),BOOK TICKETS (Hanshin Tigers vs Chunichi Dragons)
13,5/21,Thu,Osaka,Nara Deer & Final Feast,"Nara Park, Todai-ji Giant Buddha, Dotonbori Canal",Nakatanidou Mochi,Kintetsu Line,Full Nara day then return for a relaxed final night in Dotonbori.,Shika (Deer),Check Buddha hall opening times
14,5/22,Fri,Ishigaki,Tropical Arrival,"Fly to Ishigaki, Island explore, Sunset at Fusaki Beach",Ishigaki Wagyu Beef,Flight / Rental Car,Decompress after city life. Wagyu here is world-class.,"Umi (Sea), Taiyo (Sun)",Book Ishigaki flight; Reserve rental car
15,5/23,Sat,Ishigaki,Time Travel (Taketomi),"Taketomi Island, Water Buffalo Cart, Kondoi Star Sand Beach","Yaeyama Soba, Shikuwasa Juice",Ferry,Traditional coral-walled houses. A living village from 200 years ago.,Sanshin (local 3-string guitar),Ferry tickets bought at port
16,5/24,Sun,Ishigaki,Coral Reefs & Bays,"Kabira Bay (Glass-bottom boat), Shiraho Reef snorkeling","Fresh Sashimi from co-op, Umibudo (Sea grapes)",Rental Car,Kabira Bay is for views; Shiraho is for world-class snorkeling.,"Kirei (Beautiful), Sakana (Fish)",Book Glass-bottom boat (fills up on weekends)
17,5/25,Mon,Ishigaki,Jungle Adventure,"Iriomote Island, Kayak Urauchi River, Hike Pinaisara Falls, Mangroves",Island lunch pack,Ferry + Guided Tour,Physically demanding day but extraordinary payoff. Wear proper shoes.,Abunai (Dangerous/Watch out),BOOK GUIDED IRIOMOTE TOUR
18,5/26,Tue,Ishigaki,Island Drive & Sunset,"Cape Hirakubo (Lighthouse), Yonehara Beach snorkeling, Sunset Cruise",Blue Seal Ice Cream (Beni-imo flavor),Rental Car,Dramatic headland views. Sunset cruise from the port is a great addition.,Kampai! (Cheers!),Book Sunset Cruise
19,5/27,Wed,Ishigaki,Stargazing & Final Dip,"Favorite beach repeat, Scuba dive/Intro dive, Dark-sky stargazing",Local market snacks,Rental Car,Milky Way visible to the naked eye. Perfect final island night.,Hoshi (Star),Book Scuba dive (if interested)
20,5/28,Thu,Tokyo,Old Tokyo Wanders,"Yanaka Ginza (Old Tokyo), Ueno Park, Akihabara (Neon), Depachika food hall","Yanaka Ramen, Depachika grazing",Flight to Tokyo,Yanaka is the 'antidote' to Shibuya. Akihabara for your husband's browse.,Osusume wa? (What do you recommend?),Book Ishigaki-Tokyo flight
21,5/29,Fri,Tokyo,The Farewell Day,"Tsukiji Outer Market (Breakfast), Hamarikyu Gardens (Teahouse), Farewell Dinner","Tamagoyaki, Uni, Oysters, Special Send-off Meal",Local Trains,Matcha at Hamarikyu teahouse. Watch the sunset from a bridge.,Mata kimasu (I will come again),BOOK FAREWELL DINNER WELL IN ADVANCE
22,5/30,Sat,Tokyo,Return Journey,"Airport shopping (KitKats!), Airport Ramen","Airport Ramen (Fuunji or Ichiran), KitKat flavors",Narita/Haneda Express,Don't settle for bad airport food. Buy more KitKats than you think you need.,Ki o tsukete (Take care),Confirm flight check-in`;
