export const sampleCsv = `Date\tDay\tCity\tTheme\tIdeas\tMust Eats\tTransportation\tHotel\tComments
5/9\tSat\tTokyo\tArrival & Neon Lights\tLand, Shinjuku (Godzilla head), Golden Gai micro-bars, Omoide Yokocho (Memory Lane), Konbini run\tGolden Gai snacks & Omoide Yokocho Yakitori\tNarita Express\tKimpton Shinjuku Tokyo\tLanding at 2:30pm JL 55. Low pressure day for wandering. Buy Hanshin Tigers hat at Selection Store.
5/10\tSun\tTokyo\tTradition & Pop Culture\tMeiji Shrine, Yoyogi Park, Harajuku (Takeshita St), Gotokuji Temple\tHarajuku Crepes, Katsu Curry\tLocal Trains\tKimpton Shinjuku Tokyo\tArrive at Meiji Shrine by 8am to beat crowds. Quiet neighborhood dinner in Setagaya.
5/11\tMon\tTokyo\tAsakusa & Sumo\tSenso-ji Temple, Asakusa Rickshaw, Sumo Tournament, Ryogoku\tChanko Nabe (Sumo stew), Asakusa Street Food\tLocal Trains\tKimpton Shinjuku Tokyo\tRickshaw in the morning (unhurried). Sumo from 2:30-6pm.
5/12\tTue\tTokyo\tFuji & Nature\tFuji Five Lakes, Lakeside cycling, Mt. Fuji Panoramic Ropeway, Oishi Park flowers\tHoutou Noodles (local specialty)\tBus/Train to Kawaguchiko\tKimpton Shinjuku Tokyo\tMay is peak season for flower displays at Oishi Park. Peaceful day.
5/13\tWed\tTokyo\tGardens & Digital Art\tShinjuku Gyoen, Daikanyama (Tsutaya Books), Nakameguro Canal, Shibuya Crossing, TeamLab Borderless\tDaikanyama cafe lunch, Nakameguro coffee\tLocal Trains\tKimpton Shinjuku Tokyo\tSkip Tokyo Tower/Skytree. Shibuya at dusk for the neon. teamLab best in evening.
5/14\tThu\tHakone\tHakone Retreat\tHakone-Yumoto town, Ryokan relaxation, Private Onsen\tKaiseki dinner (in-room)\tRomancecar\tHotel Indigo Hakone Gora\tSlow, restorative day. Decompress in the private outdoor bath.
5/15\tFri\tHakone\tThe Hakone Loop\tAmazake Chaya, Owakudani, Open Air Museum, Lake Ashi Pirate Ship, Hakone Shrine\tBlack eggs (Kuro-tamago), Mochi and Amazake\tShinkansen to Kyoto\tHotel Indigo Hakone Gora\tStone-paved Tokaido road walk. Iconic water torii gate at late afternoon.
5/16\tSat\tKyoto\tTravel to Kyoto\tTravel from Hakone, Gion evening walk\tGion snacks, Kyoto pickles\tShinkansen\tHilton Kyoto\tLow key arrival. Evening geisha district walk is magical.
5/17\tSun\tKyoto\tZen Gardens & Gold\tFushimi Inari (6am hike), Nishiki Market, Kinkaku-ji, Ryoan-ji, Philosopher's Path, Nanzen-ji\tNishiki Market street food, Pontocho Alley dinner\tBus/Local Trains\tHilton Kyoto\tStart at Fushimi Inari by 6am. Ryoan-ji rewards stillness.
5/18\tMon\tArashiyama\tArashiyama Morning\tBamboo Grove (6am), Tenryu-ji Garden, Togetsukyo Bridge, Iwatayama Monkey Park\tTofu lunch (local specialty)\tLocal Trains\tRyotei Rangetsu\tContinue past the main bamboo grove to Jojakko-ji for hidden gems.
5/19\tTue\tOsaka\tOsaka Flavors & Old Town\tKuromon Ichiba, Shinsekai, Tennoji Garden\tTakoyaki, Kushikatsu, Market seafood\tLocal Trains\tInterContinental Osaka\tSwap Amerika-mura for the peaceful Tennoji garden.
5/20\tWed\tOsaka\tCulture & Baseball\tSumiyoshi Taisha, Hozenji Yokocho, Hanshin Tigers Game\tKoshien Curry & Yakisoba\tHanshin Line to Koshien\tInterContinental Osaka\tMoved game to tonight to free up your final night.
5/21\tThu\tOsaka\tNara Deer & Final Feast\tNara Park, Todai-ji Giant Buddha, Dotonbori Canal\tNakatanidou Mochi\tKintetsu Line\tInterContinental Osaka\tFull Nara day then return for a relaxed final night in Dotonbori.
5/22\tFri\tIshigaki\tTropical Arrival\tFly to Ishigaki, Island explore, Sunset at Fusaki Beach\tIshigaki Wagyu Beef\tFlight / Rental Car\tANA InterContinental Ishigaki\tDecompress after city life. Wagyu here is world-class.
5/23\tSat\tIshigaki\tTime Travel (Taketomi)\tTaketomi Island, Water Buffalo Cart, Kondoi Star Sand Beach\tYaeyama Soba, Shikuwasa Juice\tFerry\tANA InterContinental Ishigaki\tTraditional coral-walled houses. A living village from 200 years ago.
5/24\tSun\tIshigaki\tCoral Reefs & Bays\tKabira Bay (Glass-bottom boat), Shiraho Reef snorkeling\tFresh Sashimi from co-op, Umibudo (Sea grapes)\tRental Car\tANA InterContinental Ishigaki\tKabira Bay is for views; Shiraho is for world-class snorkeling.
5/25\tMon\tIshigaki\tJungle Adventure\tIriomote Island, Kayak Urauchi River, Hike Pinaisara Falls, Mangroves\tIsland lunch pack\tFerry + Guided Tour\tANA InterContinental Ishigaki\tPhysically demanding day but extraordinary payoff. Wear proper shoes.
5/26\tTue\tIshigaki\tIsland Drive & Sunset\tCape Hirakubo (Lighthouse), Yonehara Beach snorkeling, Sunset Cruise\tBlue Seal Ice Cream (Beni-imo flavor)\tRental Car\tANA InterContinental Ishigaki\tDramatic headland views. Sunset cruise from the port is a great addition.
5/27\tWed\tIshigaki\tStargazing & Final Dip\tFavorite beach repeat, Scuba dive/Intro dive, Dark-sky stargazing\tLocal market snacks\tRental Car\tANA InterContinental Ishigaki\tMilky Way visible to the naked eye. Perfect final island night.
5/28\tThu\tTokyo\tOld Tokyo Wanders\tYanaka Ginza (Old Tokyo), Ueno Park, Akihabara (Neon), Depachika food hall\tYanaka Ramen, Depachika grazing\tFlight to Tokyo\tInterContinental Tokyo Bay\tYanaka is the 'antidote' to Shibuya. Akihabara for your husband's browse.
5/29\tFri\tTokyo\tThe Farewell Day\tTsukiji Outer Market (Breakfast), Hamarikyu Gardens (Teahouse), Farewell Dinner\tTamagoyaki, Uni, Oysters, Special Send-off Meal\tLocal Trains\tInterContinental Tokyo Bay\tMatcha at Hamarikyu teahouse. Watch the sunset from a bridge.
5/30\tSat\tTokyo\tReturn Journey\tAirport shopping (KitKats!), Airport Ramen\tAirport Ramen (Fuunji or Ichiran), KitKat flavors\tNarita/Haneda Express\tN/A\tDon't settle for bad airport food. Buy more KitKats than you think you need.`;
